// Builds Cloudflare Pages `_headers` for the static export. A static export
// can't use per-request nonces, so each page's inline scripts are allowed by
// sha256 hash in a CSP rule scoped to exactly that route.
import { createHash } from "node:crypto";

// Apps Script answers the POST with a redirect to this host.
const LEAD_REDIRECT_HOST = "https://script.googleusercontent.com";

const BASELINE_HEADERS = [
  // No includeSubDomains until every *.prodbuilds.com host is known to be HTTPS-only.
  ["Strict-Transport-Security", "max-age=31536000"],
  ["X-Content-Type-Options", "nosniff"],
  ["X-Frame-Options", "DENY"],
  ["Referrer-Policy", "strict-origin-when-cross-origin"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=()"],
  ["Cross-Origin-Opener-Policy", "same-origin"],
];

const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g;

/** CSP source expressions for every inline executable script, deduplicated, in order. */
export function inlineScriptHashes(html) {
  const hashes = [...html.matchAll(INLINE_SCRIPT)].map(
    ([, body]) => `'sha256-${createHash("sha256").update(body).digest("base64")}'`,
  );
  return [...new Set(hashes)];
}

const leadSources = (leadEndpoint) => `'self' ${leadEndpoint} ${LEAD_REDIRECT_HOST}`;

/** Directives without script-src: safe to apply everywhere, including the 404 page. */
function baselineCsp(leadEndpoint) {
  return [
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    `form-action ${leadSources(leadEndpoint)}`,
  ].join("; ");
}

/** Full policy for one HTML route. */
export function buildCsp(hashes, leadEndpoint) {
  return [
    "default-src 'self'",
    `script-src 'self' ${hashes.join(" ")}`.trim(),
    // React, motion and Shiki emit style attributes.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    `connect-src ${leadSources(leadEndpoint)}`,
    baselineCsp(leadEndpoint),
    "upgrade-insecure-requests",
  ].join("; ");
}

const rule = (pattern, headers) =>
  [pattern, ...headers.map(([name, value]) => `  ${name}: ${value}`)].join("\n");

/**
 * Cloudflare comma-joins a header set by several matching rules, and browsers
 * enforce every policy in a joined CSP, so routes get baseline AND their own.
 *
 * @param {{ route: string, hashes: string[] }[]} pages one entry per HTML route
 * @param {string} leadEndpoint the exact Apps Script URL the forms post to
 */
export function buildHeadersFile(pages, leadEndpoint) {
  const rules = [
    "# Generated by scripts/postbuild-headers.mjs. Do not edit.",
    rule("/*", [...BASELINE_HEADERS, ["Content-Security-Policy", baselineCsp(leadEndpoint)]]),
    rule("/_next/static/*", [["Cache-Control", "public, max-age=31536000, immutable"]]),
    ...pages.map(({ route, hashes }) =>
      rule(route, [["Content-Security-Policy", buildCsp(hashes, leadEndpoint)]]),
    ),
  ];
  return `${rules.join("\n\n")}\n`;
}
